<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vinay Pandya">
<meta name="dcterms.date" content="2026-08-03">

<title>Building and Evaluating a Search Engine Over Malware-Classification Papers – Vinay Pandya</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Vinay Pandya</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../experience.html"> 
<span class="menu-text">Experience</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/vinayhpandya"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/vinay-pandya-299aa8131/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:vinayharshadpandya27@gmail.com"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#corpus-and-setup" id="toc-corpus-and-setup" class="nav-link" data-scroll-target="#corpus-and-setup">Corpus and Setup</a></li>
  <li><a href="#methodology-evaluation" id="toc-methodology-evaluation" class="nav-link" data-scroll-target="#methodology-evaluation">Methodology: Evaluation</a>
  <ul class="collapse">
  <li><a href="#relevance-labeling" id="toc-relevance-labeling" class="nav-link" data-scroll-target="#relevance-labeling">Relevance labeling</a></li>
  <li><a href="#metrics" id="toc-metrics" class="nav-link" data-scroll-target="#metrics">Metrics</a></li>
  </ul></li>
  <li><a href="#results-retrieval-quality" id="toc-results-retrieval-quality" class="nav-link" data-scroll-target="#results-retrieval-quality">Results: Retrieval Quality</a>
  <ul class="collapse">
  <li><a href="#reading-the-core-four-methods" id="toc-reading-the-core-four-methods" class="nav-link" data-scroll-target="#reading-the-core-four-methods">Reading the core four methods</a></li>
  <li><a href="#two-different-semantic-id-based-methods-two-different-stories" id="toc-two-different-semantic-id-based-methods-two-different-stories" class="nav-link" data-scroll-target="#two-different-semantic-id-based-methods-two-different-stories">Two different semantic-ID-based methods, two different stories</a></li>
  </ul></li>
  <li><a href="#generative-retrieval-what-was-actually-built" id="toc-generative-retrieval-what-was-actually-built" class="nav-link" data-scroll-target="#generative-retrieval-what-was-actually-built">Generative Retrieval: What Was Actually Built</a></li>
  <li><a href="#latency" id="toc-latency" class="nav-link" data-scroll-target="#latency">Latency</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work">Future Work</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Building and Evaluating a Search Engine Over Malware-Classification Papers</h1>
<p class="subtitle lead">A capstone project for AI-Powered Search: BM25 to generative retrieval</p>
  <div class="quarto-categories">
    <div class="quarto-category">llm</div>
    <div class="quarto-category">BM25</div>
    <div class="quarto-category">Opensearch</div>
    <div class="quarto-category">Semantic Ids</div>
    <div class="quarto-category">vector search</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Vinay Pandya </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 3, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This project builds a search engine over a corpus of arXiv malware-classification papers, implementing and comparing seven retrieval methods head-to-head: <strong>BM25 → dense (SPECTER2) → hybrid (RRF) → cross-encoder rerank → late-interaction (ColBERT via Qdrant) → k-means cluster-filtered search → generative retrieval (a trained query→semantic-ID model)</strong>.</p>
<p>Every method is evaluated on the same 40-query, LLM-judged relevance-labeled eval set, using the same NDCG@10 / MRR metrics, and benchmarked on the same latency harness. The goal was not just to build each technique, but to honestly report where each one wins, where it loses, and why — including findings that didn’t come out the way theory alone would predict.</p>
<p>Code: <a href="https://github.com/vinayhpandya/search-algorithms">github.com/vinayhpandya/search-algorithms</a></p>
</section>
<section id="corpus-and-setup" class="level2">
<h2 class="anchored" data-anchor-id="corpus-and-setup">Corpus and Setup</h2>
<ul>
<li><strong>Domain</strong>: arXiv papers on malware classification (<code>cs.CR</code>, <code>cs.LG</code>, <code>cs.CV</code> categories), collected via the <code>arxiv</code> client library across 16 search queries, deduplicated</li>
<li><strong>Enrichment</strong>: citation counts from Semantic Scholar (used later as an LTR feature)</li>
<li><strong>Index</strong>: OpenSearch, single-node local Docker setup — chosen because it supports BM25 and k-NN vector search natively in one engine, letting lexical and semantic search share the same index and fuse without cross-system round trips</li>
<li><strong>Scope decision</strong>: abstract-only (no full-text PDFs), to keep the repo small and the project achievable in a weekend — noted as future work</li>
</ul>
</section>
<section id="methodology-evaluation" class="level2">
<h2 class="anchored" data-anchor-id="methodology-evaluation">Methodology: Evaluation</h2>
<section id="relevance-labeling" class="level3">
<h3 class="anchored" data-anchor-id="relevance-labeling">Relevance labeling</h3>
<p>Manually labeling enough query-paper pairs for a meaningful eval set (857+ pairs across 40 queries) isn’t realistic by hand in the available time. Instead:</p>
<ol type="1">
<li>A <strong>researcher</strong> LLM rates each pair 0/1/2 with a rationale</li>
<li>A <strong>critic</strong> LLM reviews the researcher’s rating and either confirms or overrides it — final label = critic’s call</li>
<li>A <strong>human spot-check</strong> on a stratified sample (~65 pairs, weighted toward researcher/critic disagreements) validates the LLM labels</li>
</ol>
<p>This is standard practice for evaluating relevance judgments at scale (the same logic behind TREC-style IR evaluation and industry search-quality teams checking LLM/crowd-worker judgments) — not a shortcut.</p>
<p><strong>Known calibration issue</strong>: only ~3% of labeled pairs were rated “not relevant” (0). Because candidate pools are built from real search results (already topically adjacent to the query), the researcher/critic prompts turned out lenient about what counts as irrelevant. This doesn’t invalidate the labels — NDCG@10 still discriminates well since it weights label=2 three times as heavily as label=1 — but it does mean <strong>MRR at the standard threshold (label ≥ 1) saturates near 1.0 for every method</strong> and carries no signal. Reporting <strong>MRR at threshold ≥ 2</strong> (“how often is the very best result found immediately”) restored real discrimination between methods without needing to relabel anything. (A tighter, binary relevance rubric was designed as a follow-up fix but not run before this writeup — noted under Future Work.)</p>
</section>
<section id="metrics" class="level3">
<h3 class="anchored" data-anchor-id="metrics">Metrics</h3>
<ul>
<li><strong>NDCG@10</strong>: rewards ranking highly-relevant results near the top; uses the full graded (0/1/2) label</li>
<li><strong>MRR(≥2)</strong>: reciprocal rank of the first <em>highly</em> relevant result — the metric that actually discriminates given this corpus’s label distribution</li>
<li><strong>Latency</strong>: mean / p50 / p95 across 40 queries, local machine, no GPU</li>
</ul>
</section>
</section>
<section id="results-retrieval-quality" class="level2">
<h2 class="anchored" data-anchor-id="results-retrieval-quality">Results: Retrieval Quality</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>NDCG@10</th>
<th>MRR(≥1)</th>
<th>MRR(≥2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BM25</td>
<td>0.9003</td>
<td>1.0000</td>
<td>0.5969</td>
</tr>
<tr class="even">
<td>Dense</td>
<td>0.9026</td>
<td>1.0000</td>
<td>0.5763</td>
</tr>
<tr class="odd">
<td>Hybrid</td>
<td>0.9142</td>
<td>1.0000</td>
<td>0.7261</td>
</tr>
<tr class="even">
<td>Rerank</td>
<td>0.9131</td>
<td>1.0000</td>
<td>0.7504</td>
</tr>
<tr class="odd">
<td>Late-interaction</td>
<td>0.9003</td>
<td>1.0000</td>
<td>0.6951</td>
</tr>
<tr class="even">
<td>Semantic ID (k-means, cluster-filtered)</td>
<td>0.9624</td>
<td>0.9625</td>
<td>0.2744</td>
</tr>
<tr class="odd">
<td>Generative (RQ-VAE + trained query→ID model)</td>
<td>0.9005</td>
<td>1.0000</td>
<td>0.2432</td>
</tr>
</tbody>
</table>
<section id="reading-the-core-four-methods" class="level3">
<h3 class="anchored" data-anchor-id="reading-the-core-four-methods">Reading the core four methods</h3>
<p><strong>Dense underperforms BM25 on MRR(≥2)</strong> (0.5763 vs 0.5969) despite near-identical NDCG@10 — SPECTER2 embeddings surface broadly topical neighbors well, but are less precise than exact keyword matching at pinpointing the single best match at rank 1.</p>
<p><strong>Hybrid and rerank both correct for this</strong>, each clearly outperforming either input alone on MRR(≥2) — real evidence of fusion and reranking doing genuine work, not just reshuffling noise.</p>
<p><strong>Late-interaction lands between dense and hybrid</strong> (MRR≥2 = 0.6951) — consistent with the theoretical expectation that token-level (MaxSim) matching captures finer-grained relevance than single-vector cosine similarity, without needing full cross-attention.</p>
<p><strong>Rerank is the best quality by both metrics</strong> — expected, since a cross-encoder sees the full query and document jointly via cross-attention (strictly more expressive than any similarity-metric-based method here), at the cost of only being feasible on a pre-filtered shortlist, never the whole corpus.</p>
</section>
<section id="two-different-semantic-id-based-methods-two-different-stories" class="level3">
<h3 class="anchored" data-anchor-id="two-different-semantic-id-based-methods-two-different-stories">Two different semantic-ID-based methods, two different stories</h3>
<p>Both remaining rows use “semantic IDs” but are otherwise unrelated methods, worth not conflating:</p>
<ul>
<li><strong>Semantic ID (k-means)</strong>: a two-level k-means clustering over SPECTER2 embeddings, used to pre-filter/organize the corpus (IVF-style). Highest NDCG@10 of all seven methods (0.9624) but by far the lowest MRR(≥2) (0.2744) — it reliably finds <em>something</em> topically adjacent, but rarely the single best paper. A fixed, non-learned clustering, not a retrieval model in its own right.</li>
<li><strong>Generative retrieval</strong>: a genuinely trained model (RQ-VAE + query→ID decoder, detailed below) that predicts a semantic ID directly from the query text and looks up matching papers — the actual “generative retrieval” paradigm this project set out to test.</li>
</ul>
</section>
</section>
<section id="generative-retrieval-what-was-actually-built" class="level2">
<h2 class="anchored" data-anchor-id="generative-retrieval-what-was-actually-built">Generative Retrieval: What Was Actually Built</h2>
<p>Beyond the six baseline methods above, a from-scratch generative retrieval pipeline was implemented, following the two-stage design used in TIGER-style semantic ID systems:</p>
<p><strong>Stage 1 — RQ-VAE.</strong> A small encoder/decoder (MLP, 768→512→256→32) with a 2-level residual vector quantizer (16 codewords/level, EMA codebook updates, dead-code reset) trained on SPECTER2 embeddings to produce a hierarchical 2-digit semantic ID per paper (<code>[coarse, fine]</code>). Trained on the full 194-paper corpus; qualitative inspection showed genuinely topic-coherent clusters (e.g.&nbsp;one cluster grouped five adversarial-malware-attack papers, another grouped five malware-classification-methods papers).</p>
<p><strong>Stage 2 — query-to-ID model.</strong> Since no real user queries exist, ~1,940 synthetic (query, semantic_id) pairs were generated via LLM (10 queries per paper, mixing keyword-close and oblique natural-language phrasings). A frozen MiniLM sentence encoder + small 2-layer transformer decoder was trained to autoregressively predict a paper’s semantic ID digit-by-digit from a query, with beam search at inference time. Train/val split was done <strong>by paper</strong>, not by row, to prevent different phrasings of the same paper’s queries leaking across the split.</p>
<p><strong>Evaluation methodology.</strong> The trained model was wired into the same eval harness as the other six methods: for each of the 40 eval queries, beam search produces ranked candidate semantic IDs, each ID’s matching papers are pulled in beam order to build a ranked top-10 list, and that list is scored with the same NDCG@10/MRR machinery and LLM-judged labels used throughout.</p>
<p><strong>Result: a clear, honest negative finding.</strong> Training showed a real generalization gap — training exact-match accuracy climbed to 36% while validation exact-match stayed near 2–5%, i.e.&nbsp;the model was memorizing training-set query phrasings rather than learning to generalize across topics. This is directly reflected in the eval numbers: NDCG@10 (0.9005) looks reasonable only because the label set skews lenient (see calibration note above), while MRR(≥2) (0.2432) — the metric that actually measures whether the <em>single best</em> paper is found — is among the weakest of all seven methods. The most likely cause, and the most actionable finding: 194 papers (165 after the train/val split) is simply too little topic diversity for a 256-way discrete prediction task to generalize from — an architecture problem this isn’t; a data-scale problem it is. Scaling to a larger corpus (e.g.&nbsp;the ~100k-paper ML-ArXiv-Papers subset) is the natural next step to test that hypothesis directly.</p>
</section>
<section id="latency" class="level2">
<h2 class="anchored" data-anchor-id="latency">Latency</h2>
<p>Mean / p50 / p95 across 40 queries, local machine, no GPU:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Method</th>
<th>Mean (ms)</th>
<th>P50 (ms)</th>
<th>P95 (ms)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BM25</td>
<td>2.7</td>
<td>2.6</td>
<td>3.3</td>
</tr>
<tr class="even">
<td>Late-interaction</td>
<td>12.6</td>
<td>12.3</td>
<td>16.0</td>
</tr>
<tr class="odd">
<td>Generative</td>
<td>20.4</td>
<td>20.0</td>
<td>23.9</td>
</tr>
<tr class="even">
<td>Semantic ID (k-means)</td>
<td>30.5</td>
<td>30.4</td>
<td>36.0</td>
</tr>
<tr class="odd">
<td>Dense</td>
<td>42.7</td>
<td>42.7</td>
<td>48.0</td>
</tr>
<tr class="even">
<td>Hybrid</td>
<td>59.6</td>
<td>59.4</td>
<td>64.8</td>
</tr>
<tr class="odd">
<td>Rerank</td>
<td>187.8</td>
<td>186.8</td>
<td>200.9</td>
</tr>
</tbody>
</table>
<p>BM25 is fastest by a wide margin, as expected — no model inference at all. Generative retrieval lands in the middle of the pack: slower than BM25 and late-interaction, but notably faster than dense search despite also requiring a forward pass, since the query encoder here (frozen MiniLM) is far smaller than SPECTER2, and lookup after ID prediction is a cheap dictionary access rather than a k-NN search over the full corpus. Rerank is the clear latency outlier, consistent with cross-encoders’ cost scaling with the number of candidates scored, not just query size — the tradeoff that pairs it with a cheap first-stage retriever in practice rather than running it corpus-wide.</p>
</section>
<section id="future-work" class="level2">
<h2 class="anchored" data-anchor-id="future-work">Future Work</h2>
<ul>
<li><strong>Rerun evaluation under a binary (0/1), query-specific relevance rubric</strong> — designed to fix the labeling calibration issue described above, but not executed before this writeup.</li>
<li><strong>Scale the corpus</strong> (e.g.&nbsp;to the ~100k-paper ML-ArXiv-Papers subset) to directly test whether generative retrieval’s weak MRR(≥2) is a data-scale problem, as the evidence here suggests, rather than an architectural one.</li>
<li><strong>Hypencoders</strong> Testing a small Qnet and hype-encoder based network, want to see how fast it is to train and how well the NDCG scores are</li>
<li><strong>Full-text PDFs and a RAG QA layer</strong> on top of the retrieval stack — scoped out from the very beginning to keep this project achievable in the available time.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/vinayhpandya\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>© 2025 Vinay Pandya</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>